import { useState } from 'react';
import { Container, Row, Col, Card, Form, Button, Alert, Navbar } from 'react-bootstrap';

import { verify2FA, cancel2FA } from '../API/API.js';

function TotpForm({ onSuccess, onCancel }) { // onSuccess = handle2FASuccess, onCancel = setTwoFactorRequired(false) in App.jsx
    const [token, setToken] = useState('');
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);

    const handleSubmit = async (event) => {
        event.preventDefault();

        setError('');

        if (!/^\d{6}$/.test(token)) {
            setError('The TOTP code must contain exactly 6 digits.');
            return;
        }

        setLoading(true);

        try {
            const result = await verify2FA(token); // from API
            onSuccess(result);
        } catch (err) {
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    const handleBackToLogin = async () => {
        try {
            setError('');
            setLoading(true);

            await cancel2FA();

            onCancel();
        } catch (err) {
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <>
            <Navbar variant="dark" className="mb-4 px-3 navbar-brand-custom">
                <Navbar.Brand>Sport Facility Reservation</Navbar.Brand>
            </Navbar>

            <Container>
                <Row className="justify-content-center">
                    <Col md={6} lg={4}>
                        <Card className="card-custom">
                            <Card.Header>Two-Factor Authentication</Card.Header>
                            <Card.Body>
                                <p>
                                    Enter the 6-digit code generated by your authenticator app.
                                </p>

                                {error && (
                                    <Alert variant="danger" dismissible onClose={() => setError('')}>
                                        {error}
                                    </Alert>
                                )}

                                <Form onSubmit={handleSubmit}>
                                    <Form.Group className="mb-3">
                                        <Form.Label>TOTP code</Form.Label>
                                        <Form.Control type="text" inputMode="numeric" maxLength={6} value={token} onChange={(event) => setToken(event.target.value)} required/>
                                    </Form.Group>

                                    <div className="d-flex">
                                        <Button type="submit" className="btn-brand" disabled={loading || token.length !== 6}>
                                            {loading ? 'Verifying...' : 'Verify'}
                                        </Button>

                                        <Button type="button" variant="outline-secondary" className="ms-2" disabled={loading} onClick={handleBackToLogin}>
                                            Back to Login
                                        </Button>
                                    </div>
                                </Form>
                            </Card.Body>
                        </Card>
                    </Col>
                </Row>
            </Container>
        </>
    );
}

export default TotpForm;